[package]
name = "framework"
version.workspace = true
edition = "2024"

[dependencies]
serde.workspace = true
serde_json = "*"
serde_html_form = "*"
smallvec = { version = "1", features = ["serde"] }

time = { version = "*", features = ["formatting", "parsing", "macros"] }

tokio.workspace = true
tokio-util = { version = "*", features = ["rt", "io"] }
tokio-stream = "*"

http = "*"
http-body = "*"
http-body-util = "*"
hyper = { version = "*", features = ["server", "http1", "http2"] }
hyper-util = { version = "*", features = ["tokio", "server-auto", "server-graceful", "client-legacy"] }
percent-encoding = "*"

reqwest = { version = "0", features = ["stream"] }
# for FallbackDnsResolver to be used as hyper resolver
tower-service = "*"

# dependency-only, for their compile time max level features; see spec/third_party_instrumentation.md
tracing = { version = "*", features = ["release_max_level_off"] }
log = { version = "*", features = ["release_max_level_off"] }

futures = "*"
pin-project-lite = "*"
bytes = "*"
libc = "*"
memchr = "*"
rand = "*"

[lints]
workspace = true
