[package]
name = "framework_http"
version.workspace = true
edition = "2024"

[dependencies]
framework.workspace = true
serde.workspace = true
serde_html_form = "*"
tokio.workspace = true
tokio-util = { version = "*", features = ["io"] }
futures = "*"

http = "*"
http-body = "*"
http-body-util = "*"
hyper = { version = "*", features = ["server", "http1", "http2"] }
hyper-util = { version = "*", features = ["tokio", "server-auto", "server-graceful"] }
bytes = "*"
httpdate = "*"
percent-encoding = "*"

[lints]
workspace = true
