[analytics]
reporting_enabled = false
check_for_updates = false

[news]
news_feed_enabled = false

[snapshots]
# set to false to remove snapshot functionality
enabled = false

[unified_alerting]
enabled = false

[users]
default_theme = dark

[log]
level = info

[plugins]
plugin_admin_enabled = false
# Enter a comma-separated list of plugin identifiers to avoid loading (including core plugins). These plugins will be hidden in the catalog.
disable_plugins = grafana-lokiexplore-app,grafana-pyroscope-app,grafana-metricsdrilldown-app,grafana-exploretraces-app

# Comma separated list of plugin ids to install as part of the startup process.
# These will be installed, by default, asynchronously (in the background) while starting Grafana.
preinstall = grafana-clickhouse-datasource

[auth.anonymous]
enabled = true
org_role = Viewer

[security]
# default admin user, created on startup
admin_user = admin
# default admin password, can be changed before first start of grafana, or in profile settings
admin_password = admin
