services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ulimits:
      nofile: 262144
    volumes:
      - ./config.d/custom_config.xml:/etc/clickhouse-server/config.d/custom_config.xml
    #   - ./users.d/viewer.xml:/etc/clickhouse-server/users.d/viewer.xml
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 8123:8123
      - 9000:9000
