use axum::Router;
use axum::extract::State;
use axum::response::IntoResponse as _;
use axum::response::Response;
use bytes::Bytes;
use http::header;

use crate::api::ApiDefinition;
use crate::api::ServiceDefinition;
use crate::api::TypeRegistry;
use crate::json;
use crate::web::route::get;

/// collects api definitions of all `#[api]` services, and exposes them via `GET /_sys/api`
/// ```text
/// let mut apis = ApiRegistry::new(env!("CARGO_PKG_NAME"));
/// apis.add(UserServiceImpl::api_definition);
/// let app = app.merge(apis.routes());
/// ```
pub struct ApiRegistry {
    app: &'static str,
    services: Vec<ServiceDefinition>,
    types: TypeRegistry,
}

impl ApiRegistry {
    pub fn new(app: &'static str) -> Self {
        Self { app, services: vec![], types: TypeRegistry::default() }
    }

    /// pass the `api_definition` fn generated by `#[api]`, e.g. `apis.add(UserServiceImpl::api_definition)`.
    pub fn add(&mut self, definition: impl FnOnce(&mut TypeRegistry) -> ServiceDefinition) {
        let service = definition(&mut self.types);
        assert!(
            !self.services.iter().any(|existing| existing.name == service.name),
            "duplicate api service name, name={}",
            service.name
        );
        self.services.push(service);
    }

    /// services and operations are sorted by name, so output is canonical and can be compared between versions.
    pub fn definition(self) -> ApiDefinition {
        let mut services = self.services;
        services.sort_by(|left, right| left.name.cmp(&right.name));
        for service in &mut services {
            service.operations.sort_by(|left, right| left.name.cmp(&right.name));
        }
        ApiDefinition { app: self.app.to_owned(), services, types: self.types.into_types() }
    }

    // definition is built and serialized eagerly, so type name conflicts fail at startup
    pub fn routes(self) -> Router {
        let definition = self.definition();
        let json = json::to_json(&definition).expect("failed to serialize api definition");
        Router::new().route("/_sys/api", get(api_definition)).with_state(Bytes::from(json))
    }
}

async fn api_definition(State(json): State<Bytes>) -> Response {
    ([(header::CONTENT_TYPE, "application/json")], json).into_response()
}

#[cfg(test)]
mod tests {
    use std::any::type_name;

    use crate::api::ApiType;
    use crate::api::Constraints;
    use crate::api::FieldDefinition;
    use crate::api::OperationDefinition;
    use crate::api::TypeDefinition;
    use crate::api::TypeRef;

    use super::*;

    struct Request;

    impl ApiType for Request {
        fn type_ref(registry: &mut TypeRegistry) -> TypeRef {
            if registry.reserve("Request", type_name::<Self>()) {
                let fields = vec![FieldDefinition {
                    name: "name".to_owned(),
                    r#type: <String as ApiType>::type_ref(registry),
                    constraints: Constraints { not_blank: true, ..Constraints::default() },
                }];
                registry.define(TypeDefinition::Struct { name: "Request".to_owned(), fields });
            }
            TypeRef::Ref { name: "Request".to_owned() }
        }
    }

    fn user_service(registry: &mut TypeRegistry) -> ServiceDefinition {
        ServiceDefinition {
            name: "UserService".to_owned(),
            operations: vec![
                OperationDefinition {
                    name: "update".to_owned(),
                    method: "PUT".to_owned(),
                    path: "/user/update".to_owned(),
                    request: <Request as ApiType>::optional_type_ref(registry),
                    response: <Result<(), ()> as ApiType>::optional_type_ref(registry),
                },
                OperationDefinition {
                    name: "create".to_owned(),
                    method: "POST".to_owned(),
                    path: "/user/create".to_owned(),
                    request: <Request as ApiType>::optional_type_ref(registry),
                    response: <Result<String, ()> as ApiType>::optional_type_ref(registry),
                },
            ],
        }
    }

    #[test]
    fn build_definition() {
        let mut apis = ApiRegistry::new("demo");
        apis.add(user_service);
        let definition = apis.definition();

        assert_eq!(definition.app, "demo");
        assert_eq!(definition.services.len(), 1);
        let operations = &definition.services[0].operations;
        assert_eq!(operations[0].name, "create");
        assert_eq!(operations[1].name, "update");
        assert_eq!(operations[1].response, None);
        assert_eq!(definition.types.len(), 1);

        let json = json::to_json(&definition).unwrap();
        assert_eq!(
            json,
            r#"{"app":"demo","services":[{"name":"UserService","operations":[{"name":"create","method":"POST","path":"/user/create","request":{"kind":"ref","name":"Request"},"response":{"kind":"String"}},{"name":"update","method":"PUT","path":"/user/update","request":{"kind":"ref","name":"Request"},"response":null}]}],"types":[{"kind":"struct","name":"Request","fields":[{"name":"name","type":{"kind":"String"},"constraints":{"not_blank":true}}]}]}"#
        );
    }

    #[test]
    #[should_panic(expected = "duplicate api service name")]
    fn duplicate_service_name() {
        let mut apis = ApiRegistry::new("demo");
        apis.add(user_service);
        apis.add(user_service);
    }
}
