steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - app/${_APP}/Dockerfile
      - -t
      - ${_REPOSITORY}/${_APP}:${_VERSION}
      - -t
      - ${_REPOSITORY}/${_APP}:latest
      - .
images:
  - ${_REPOSITORY}/${_APP}:${_VERSION}
  - ${_REPOSITORY}/${_APP}:latest
timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
tags: ["${_APP}"]
substitutions:
  _APP: log_processor
